### ISSUE TITLE
ModuleNotFoundError: No module named 'pyrelay'

### ISSUE THREAD

**Issue by adrianzhang** [johnny423/pyrelay#5]
Followed README, run pyrelay locally. requirement file installed. in cloned pyrelay folder.

```
python ./pyrelay/relay/server.py

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3
```

```
python3 ./pyrelay/relay/server.py
Traceback (most recent call last):
  File "./pyrelay/relay/server.py", line 6, in <module>
    from pyrelay.nostr.serialize import loads
ModuleNotFoundError: No module named 'pyrelay'
```

**Comment by adrianzhang** [comment]
And if using docker 

```
docker compose up
docker: 'compose' is not a docker command.
See 'docker --help'
```

**Comment by adrianzhang** [comment]
> And if using docker
> 
> ```
> docker compose up
> docker: 'compose' is not a docker command.
> See 'docker --help'
> ```

Well compose problem solved. local installation is still not available. 

```
oem@CHIA01:~/pyrelay$ python --version
Python 3.11.2
oem@CHIA01:~/pyrelay$ python ./pyrelay/relay/server.py
Traceback (most recent call last):
  File "/home/oem/pyrelay/./pyrelay/relay/server.py", line 4, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'
oem@CHIA01:~/pyrelay$ 
oem@CHIA01:~/pyrelay$ python pyrelay/relay/server.py
Traceback (most recent call last):
  File "/home/oem/pyrelay/pyrelay/relay/server.py", line 4, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'
oem@CHIA01:~/pyrelay$ ls
backend.dockerfile  LICENSE.md  pyproject.toml  README.md             requirements-tests.txt  scripts
docker-compose.yml  mypy.ini    pyrelay         requirements-dev.txt  requirements.txt        tests
oem@CHIA01:~/pyrelay$ 


```
